/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookMovieIdRouteImport } from './routes/book.$movieId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMovieIdRoute = BookMovieIdRouteImport.update({
  id: '/book/$movieId',
  path: '/book/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tickets': typeof TicketsRoute
  '/book/$movieId': typeof BookMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tickets': typeof TicketsRoute
  '/book/$movieId': typeof BookMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tickets': typeof TicketsRoute
  '/book/$movieId': typeof BookMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies' | '/tickets' | '/book/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies' | '/tickets' | '/book/$movieId'
  id: '__root__' | '/' | '/movies' | '/tickets' | '/book/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesRoute: typeof MoviesRoute
  TicketsRoute: typeof TicketsRoute
  BookMovieIdRoute: typeof BookMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$movieId': {
      id: '/book/$movieId'
      path: '/book/$movieId'
      fullPath: '/book/$movieId'
      preLoaderRoute: typeof BookMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesRoute: MoviesRoute,
  TicketsRoute: TicketsRoute,
  BookMovieIdRoute: BookMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
